---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ${{values.name | dump}}
  annotations:
    backstage.io/kubernetes-namespace: "${{values.namespace}}"
spec:
  predictor:
    model:
      modelFormat:
        name: ${{values.name | dump}}
      storageUri: ${{values.url}}